### ISSUE TITLE
I HATE ICONS IN TKINTER!!!!!

### ISSUE THREAD

**Issue by charlie-sans** [charlie-sans/PythonicOS#31]
I HATE ICONS IN TKINTER!!!!!

i wanted to see if i could add icons to the widgets on the desktop so they wont be a solid color.

when i tried to do that i wouldn't find the path to the DAMN PICTURESSS AHHHHH.

if you want to give it a go, just point the picture path to the system/bin folder in the load_files_thread() functions if ext ==, as that contains every system picture/icon that you could use.

and when you do figure out how to do it PLEASE submit a issue with the changes that you made and ill add them.

_Originally posted by @charlie-sans in https://github.com/OpenStudioCorp/PythonicOS/discussions/29#discussioncomment-6153769_

**Comment by h4rldev** [comment]
Then stop using tkinter, it's quite shit

**Comment by charlie-sans** [comment]
> Then stop using tkinter, it's quite shit

I've tried to use PyQT but it's too difficult and is hard to understand.

**Comment by charlie-sans** [comment]
If you have a better way of making a gui then let me know

**Comment by h4rldev** [comment]
PyQT is hard because it's a large toolkit, that's why it's useful to learn

**Comment by charlie-sans** [comment]
ill do picture things later, but ima learn pyqt and use that for any other apps
